**01/12/2026** SNAS

In [11]:
import sys
print("Python version:", sys.version)
print("Executable:", sys.executable)

Python version: 3.14.0 (tags/v3.14.0:ebf955d, Oct  7 2025, 10:15:03) [MSC v.1944 64 bit (AMD64)]
Executable: c:\Users\user\AppData\Local\Programs\Python\Python314\python.exe


In [3]:
import numpy as np

np.__version__

'2.3.5'

In [12]:
import sys, numpy
print("Python:", sys.executable)
print("NumPy location:", numpy.__file__)

Python: c:\Users\user\AppData\Local\Programs\Python\Python314\python.exe
NumPy location: c:\Users\user\AppData\Local\Programs\Python\Python314\Lib\site-packages\numpy\__init__.py


**Task 1**

In [ ]:
line = np.linspace(0, 1, 10)
line = np.round(line, 1)

line

# the result should be this:
# [0 0.1 0.2 0.3]

array([0. , 0.1, 0.2, 0.3, 0.4, 0.6, 0.7, 0.8, 0.9, 1. ])

In [8]:
np.zeros((3, 3))
np.ones((4, 3))

# take in tuples of shape, and return arrays

# random numbers class in numpy
# numbers

np.random.seed(43)

# randomArray = np.random.rand(3, 4)
# randomArray

randomArray = np.random.randint(0, 100, (3, 3))  # start, stop, (shape)
randomArray

array([[68, 64, 49],
       [21, 58, 16],
       [51, 17, 59]], dtype=int32)

**Task 2**
- create a list of 1 to 10
- use list comprehension
- give me the addition of numbers from 1 to 10

In [7]:
data = np.array(range(1, 11))
print(data)
print(data.sum())

[ 1  2  3  4  5  6  7  8  9 10]
55
