**01/12/2025** SNAS

In [2]:
import sys
print (sys.executable)

c:\Users\user\AppData\Local\Programs\Python\Python314\python.exe


In [3]:
import numpy as np

In [4]:
np.__version__

'2.3.5'

When ever we are using . notation, dot notation, we are trying to access the methods within a class

numpy.__version__ attribute within the numpy class

In [4]:
python_list = [1,2,3,"string",6.7]


numslist = [x for x in range(10)]
print(numslist)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [5]:
print(numslist*3)
print(type(numslist))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>


In [6]:
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [7]:
print(arr1*3)
print(type(arr1))

[ 3  6  9 12 15]
<class 'numpy.ndarray'>


In [8]:
arr1D = np.array([1,  2,  3])
print(arr1D,"\n",arr1D.ndim)

[1 2 3] 
 1


In [9]:
arr2D = np.array([[1,  2,  3],
                  [1,  2,  3]])

print(arr2D,"\n",arr2D.ndim)

[[1 2 3]
 [1 2 3]] 
 2


In [10]:
arr3D = np.array([[[1,  2,  3],[1,  2,  3]],
                  [[1,  2,  3],[1,  2,  3]]])

print(arr3D,"\n",arr3D.ndim)

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]] 
 3


In [11]:
# ndim works on objects, and checks their dimensions

print(f"dimensions are: {arr1D.ndim}")

print(f"dimensions are: {arr2D.ndim}")

print(f"dimensions are: {arr3D.ndim}")


# using np.shape method, for checking the dimensions of an array!!!
# (rows, columns)

print(f"shape is: {np.shape(arr1D)}")

print(f"shape is: {np.shape(arr2D)}")

print(f"shape is: {np.shape(arr3D)}")

# both ways work
np.ndim(arr1D)
arr1D.shape

# size, how large array is, how many elements there are in the array


# 

arr1D.dtype

dimensions are: 1
dimensions are: 2
dimensions are: 3
shape is: (3,)
shape is: (2, 3)
shape is: (2, 2, 3)


dtype('int64')

In [12]:
shape1D = arr1D.ndim
shape1D

size1D = arr1D.size
size1D

size2D = arr2D.size
size2D

size3D = arr3D.size
size3D

12

In [13]:
print(arr1D)

[1 2 3]


In [14]:
# broadcasting 

arr1D * 30

arr1D + arr1D 

array([2, 4, 6])

In [15]:
arr1 = np.array([1,2,3])
print(arr1)

arr2 = np.array([10,20,30])
print(arr2)

print("result: ", arr1 ** arr2)

[1 2 3]
[10 20 30]
result:  [              1         1048576 205891132094649]


In [16]:
a = 10
b = 3
print(a + b) # Addition: 13
print(a - b) # Subtraction: 7
print(a * b) # Multiplication: 30
print(a / b) # Division: 3.333
print(a // b) # Floor Division: 3
print(a % b) # Modulus: 1
print(a ** b) # Exponentiation: 1000

13
7
30
3.3333333333333335
3
1
1000


In [17]:
3**30

205891132094649

In [18]:
prices = np.array([4000000,3500000,2500000])
print(f"The prices are: {prices/1000000} million") # scale data

The prices are: [4.  3.5 2.5] million


slicing
reshaping

In [19]:
# arange
# easiest way to create  an array quickly 

range_of_numbers = np.arange(1,11)
range_of_numbers.reshape(5,2)
print(range_of_numbers)

# exactly same as this
range_example = np.arange(1,11).reshape(5,2)
print(range_example)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [ ]:
# only list comprehension we have used
nums = [x for x in range(0,101,2)] 
print(nums)

nums_arr = np.array(nums)   #SNAS: this syntax I added my own to find size of array

print(nums_arr.size)    #SNAS: this syntax I added my own to know the number of elements in nums, must first put it into an array

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]
51


In [23]:
# 

nums1 = nums[100:0:-1] # accessing elements in list


arraynums = np.array(nums)
print(arraynums)

print(arraynums[:])

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [24]:
line = np.linspace(0,1,10) # values are evenly spaced and stored in array

line

# the result should be this:
# [ 0 0.1 0.2 0.3 0.4 ... ]

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [25]:
np.zeros((3,3))
np.ones((3,3))

# take in tuples of shape, and return arrays

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
# random class in numpy 
# numbers 


np.random.seed(40) # helps number reproducibility 

# randomArray = np.random.rand(3,4)
# randomArray

randomArray = np.random.randint(0,100,(3,2)) # start, stop, (shape)
randomArray

array([[70, 91],
       [ 7, 37],
       [56, 50]], dtype=int32)

Change and reshape

transform, linear algebra

In [ ]:
flatarray = randomArray.flatten()
flatarray

reshapedarray = flatarray.reshape(3,2)  #SNAS: I've corrected this because sir syntax below giving error
#reshapedarray = flatarray.reshape(6,2)  #SNAS: <-- sir input, but this syntax giving error
print(reshapedarray)

[[70 91]
 [ 7 37]
 [56 50]]


In [34]:
# transform
reshapedarray.T

array([[70,  7, 56],
       [91, 37, 50]], dtype=int32)

In [35]:
# aggregations 

data = np.array([85,94,22,68,94,54,98]) # marks

# sum
# mean
# min max

# print(data.sum())

np.sum(data)

# create a list of 1 to 10
# use list comprehension
# give me the addition of numbers from 1 to 10

array_idrees = np.array([num for num in range(1,11)])
sum_of_array_idrees = array_idrees.sum()
print(sum_of_array_idrees)
array_idrees.mean()

# list comprehension - [ number : expression ]

55


np.float64(5.5)

Whole thinggggg:::

but, we can also go, column wise

or

row wise

In [36]:
a_2d_matrix = np.ones((3,5))

print(a_2d_matrix)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [37]:
# columm wise sum

a_2d_matrix.sum(axis=0)

a_2d_matrix.sum(axis=1) # row wise sum

array([5., 5., 5.])

**splitting numpy arrays**

In [38]:
# exactly same as this
dataset_array = np.arange(1,101).reshape(50,2)
# print(dataset_array)


# x input ----->  y output

# 1 ------> 2

# rows are 50


train_dataset = dataset_array[:25] # 70 rows

test_dataset = dataset_array[25:] # All the rows


print(test_dataset)

[[ 51  52]
 [ 53  54]
 [ 55  56]
 [ 57  58]
 [ 59  60]
 [ 61  62]
 [ 63  64]
 [ 65  66]
 [ 67  68]
 [ 69  70]
 [ 71  72]
 [ 73  74]
 [ 75  76]
 [ 77  78]
 [ 79  80]
 [ 81  82]
 [ 83  84]
 [ 85  86]
 [ 87  88]
 [ 89  90]
 [ 91  92]
 [ 93  94]
 [ 95  96]
 [ 97  98]
 [ 99 100]]
