**10/12/2025**

- Things about Linear Algebra
- Scalers
- Vectors
- Matrices
- Dot product
- Matrix product
- memory works and accessing

Why do we study linear algebra in AI
- we do a lot of calculations
- we deal with a lot indices, matrixes, dimensions
- to help build AI model

so far, we have dealt with a lot of data.
- data most of the operations that we did, are based on linear algebra
- lists and arrays
- dictionary, but you have save data
- linear structures
- pandas

how to manipulate this data to get better outputs

- lists
- list accessing
- arrays, accessing
- broadcasting
- linear algebra with matrices
- maths
    - calculus

data - 

- iris: [sepal_length, sepal_width, species]
- titanic: [pclass, sibling, spouse, fare, age, gender, survival]
- tips: []
- penguins [species, island, length, weight]

columns = vectors

In [ ]:
list2 = [3,4,5,'nazihah',4,5,[3,45,5]]
list2[6]

#SNAS: list can stores many types of arguments, we can store list within list as well
#SNAS: list is heterogenous
#SNAS: to access an argument inside list must index in integer format only

[3, 45, 5]

In [22]:
vector1 = [10,4,10]

vector2 = [20,4,10]

vector3 = [30,4,10]

len(vector1)

#SNAS: in Python simple list can help us to define vector

3

**Exercise 1**


In [23]:
# [2,4,10] as a result
matrix2 = [vector1,vector2,vector3]
matrix2[1]

[20, 4, 10]

In [20]:
# 2 as a result
matrix2[1][0]

2

In [24]:
type(matrix2)

list

In [ ]:
sum(vector1)    #SNAS: Python method to calculate sum
len(vector1)    #SNAS: count of elements

In [25]:
import numpy as np

In [ ]:
arr = np.array(vector1)
arr
#SNAS: vector1 itself is a list, but above syntax makes the vector1 list into an array

arr.mean()
arr.max()
arr.min()
arr.std()
#SNAS: to access function under numpy, use dot method

In [26]:
vector1 = [10,4,10]
vector2 = [20,4,10]
vector3 = [30,4,10]

matrix = [vector1,
          vector2,
          vector3]

matrix

[[10, 4, 10], [20, 4, 10], [30, 4, 10]]

In [27]:
matrix[0][2]    # row x column

10

In [ ]:
matrix = [[10,4,10],    #row0
          [20,4,10],    #row1
          [30,4,10],    #row2
          [30,4,10]]    #row3

matrixarr = np.array(matrix)

#SNAS: pass list of vectors into an array matrixarr

In [ ]:
matrixarr[1:3][1]

#SNAS: to pick up indexes to show, it won't be showing the intended last index. meaning 3, it won't show arguments at 3, but before that. it won't include at index 3

array([30,  4, 10])

In [47]:
matrixarr * 2   # scalar multiplication

# scalar operations with arrays
# 
matrix * 2

[[10, 4, 10],
 [20, 4, 10],
 [30, 4, 10],
 [30, 4, 10],
 [10, 4, 10],
 [20, 4, 10],
 [30, 4, 10],
 [30, 4, 10]]

In [ ]:
matrix2 = [[vector1],
          [vector2],
          [vector3]]

matrixarr2 = np.array(matrix2)

In [40]:
type(matrixarr)

numpy.ndarray

In [41]:
matrixarr.ndim

2

In [48]:
matrixarr.shape # how many rows & columns

(4, 3)

In [42]:
matrixarr[0:2][1]

array([20,  4, 10])

In [43]:
matrixarr[0:2][0]   # rows from 0 to 2, it will take it as a new set of list

array([10,  4, 10])

In [ ]:
# broadcasting

matrixarr + 100

array([[110, 104, 110],
       [120, 104, 110],
       [130, 104, 110],
       [130, 104, 110]])

In [ ]:
# broadcasting need to have the same shape

a = np.array([1, 3, 5])
b = np.array([10, 10, 10])

a + b

array([11, 13, 15])

In [54]:

a = np.array([[1, 3, 5, 6],
             [2, 8, 7, 9]])
b = np.array([10, 10, 10, 10])

print(a + b)
print(a * b)
print(a / b)
print(a + b)

[[11 13 15 16]
 [12 18 17 19]]
[[10 30 50 60]
 [20 80 70 90]]
[[0.1 0.3 0.5 0.6]
 [0.2 0.8 0.7 0.9]]
[[11 13 15 16]
 [12 18 17 19]]


In [ ]:
a = np.array([[1, 3, 5, 6],
             [2, 8, 7, 9]])
b = np.array([[10],
             [100]])

print(a + b)
print(a * b)
print(a / b)
print(a + b)
#print(a @ b)    #SNAS: matrix multiplication, need to change the size of multiplication

In [57]:
variance = np.array([145325, 423542, 24355, 3523456])
#SNAS: 

n = np.array([145, 542, 355, 3456])

In [58]:
(variance**0.5).round(2)

array([ 381.22,  650.8 ,  156.06, 1877.09])

In [ ]:
covariance = np.array([145325, 423542])

n = np.array([145, 542, 355, 3456])

stdx, stdy = 

stdx

r = covariance


In [59]:
x = np.array([[1,4,1],
              [2,5,2]])
 
w = np.array([10,10,10])
 
matmultiply_xw = np.dot(x,w)
matmultiply_xw

array([60, 90])

In [60]:
w2 = np.array([[10,2,3],
              [10,2,3],
              [10,2,3]])

matmultiply_xw2 = np.dot(x,w2)
matmultiply_xw2

array([[60, 12, 18],
       [90, 18, 27]])

**Arrays vs. Lists**
- arrays are faster, huge data
- list arrays for 100< numbers
- arrays significantly
- array methods

In [1]:
import numpy as np

In [ ]:
hetero = np.array([1,2,'1222','idrees',5,4])
hetero

#SNAS: list can hold different type of data but array can't. Array will change all arguments inside list into dtype U21

array(['1', '2', '1222', 'idrees', '5', '4'], dtype='<U21')

In [ ]:
hetero = np.array([1,2,3,5,5])
hetero.dtype

#SNAS: optimum use of array is to save only one type of data like only integer, string etc

dtype('int64')

In [ ]:
hetero = np.array(['idrees', 'ibrahim', 'mel', 'hazira'])
hetero.dtype

#SNAS: U7 is the data type for string

dtype('<U7')

**Exercise**

In [ ]:
A = np.array(
[[2, 3, 4],
[6, 7, 8],
[3, 2, 3]])

#SNAS: A shape = 3 x 3

B = np.array([
[5, 5, 5],
[2, 2, 2],])

#SNAS: B shape = 2 x 3

B@A #SNAS: the result shape will be 2 x 3

array([[55, 60, 75],
       [22, 24, 30]])

In [16]:
A = np.array(
[[5, 5, 5],
[2, 2, 2],
[5, 5, 5]])

B = np.array(
[[3, 3, 3],
[3, 3, 3],
[3, 3, 3]])

print('Matrix multiplication A@B: \n', A@B, '\n')
print('Array multiplication A*B: \n', A*B)
print('_________________________')
print('Matrix multiplication B@A: \n', B@A, '\n')
print('Array multiplication B*A: \n', B*A)

Matrix multiplication A@B: 
 [[45 45 45]
 [18 18 18]
 [45 45 45]] 

Array multiplication A*B: 
 [[15 15 15]
 [ 6  6  6]
 [15 15 15]]
_________________________
Matrix multiplication B@A: 
 [[36 36 36]
 [36 36 36]
 [36 36 36]] 

Array multiplication B*A: 
 [[15 15 15]
 [ 6  6  6]
 [15 15 15]]
