**31/12/2025**

In [ ]:
# pip install torch

   ---------------------------------------- 0.0/110.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/110.9 MB ? eta -:--:--
    --------------------------------------- 2.1/110.9 MB 7.6 MB/s eta 0:00:15
   - -------------------------------------- 4.2/110.9 MB 8.5 MB/s eta 0:00:13
   -- ------------------------------------- 6.6/110.9 MB 9.2 MB/s eta 0:00:12
   --- ------------------------------------ 8.7/110.9 MB 9.5 MB/s eta 0:00:11
   ---- ----------------------------------- 11.3/110.9 MB 9.9 MB/s eta 0:00:11
   ---- ----------------------------------- 13.4/110.9 MB 10.0 MB/s eta 0:00:10
   ----- ---------------------------------- 15.5/110.9 MB 10.0 MB/s eta 0:00:10
   ------ --------------------------------- 17.6/110.9 MB 10.0 MB/s eta 0:00:10
   ------- -------------------------------- 20.2/110.9 MB 10.1 MB/s eta 0:00:10
   -------- ------------------------------- 22.8/110.9 MB 10.3 MB/s eta 0:00:09
   -------- ------------------------------- 24.9/110.9 MB 10.3 MB/s

In [1]:
import torch as th
import torch

In [2]:
# Scalar tensor
t_scalar = th.tensor(5)

In [3]:
# 1 D tensor

t_1D = th.tensor([1,2,3,4])

t_1D.shape

torch.Size([4])

In [4]:
# 2 D tensor

t_2D = th.tensor([[1, 2, 3, 4],
                  [1, 2, 3, 4],
                  [1, 2, 3, 4],
                 ])

t_2D.shape

torch.Size([3, 4])

In [5]:
# 3 D tensor

t_3D = th.tensor([
                 [[1, 2, 3, 4], [1, 2, 3, 4]],
                 [[1, 2, 3, 4], [1, 2, 3, 4]],
                 [[1, 2, 3, 4], [1, 2, 3, 4]]
                 ])

t_3D.shape

torch.Size([3, 2, 4])

In [6]:
# operations
# broadcasting works
t_2D + 10

tensor([[11, 12, 13, 14],
        [11, 12, 13, 14],
        [11, 12, 13, 14]])

In [7]:
# generate a tensor

gen_ten = th.rand(2,5,3)

gen_ten.to(device=de)
gen_ten

NameError: name 'de' is not defined

In [8]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

In [9]:
tensor_B.shape

torch.Size([3, 2])

In [10]:
# 7   8     9
# 10  11   12

x = tensor_B.T
x

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])

In [11]:
tensor_A @ tensor_B

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [12]:
output = torch.matmul(tensor_A, tensor_B.T)
output

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [13]:
x

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])

In [14]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)

# This uses matrix multiplication
linear = torch.nn.Linear(in_features  =2, # in_features = matches inner dimension of input 
                         out_features =6) # out_features = describes outer value 

linear

Linear(in_features=2, out_features=6, bias=True)

In [15]:
x = tensor_A

In [16]:
output = linear(x)
output

tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

In [17]:

print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])
